import { useState } from "react";
import { Bell, Lock, Save, ShieldCheck, UserCog } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Field, Panel, PanelTitle, SelectInput, TextInput } from "@/components/habti/ui-bits";
import { useHabti } from "@/lib/habti-store";

export function ParametresCompteView() {
  const { notify } = useHabti();
  const [notif, setNotif] = useState({ navigateur: true, email: true, mobile: false });
  const [doubleAuth, setDoubleAuth] = useState(true);
  return <div className="module-stack"><Tabs defaultValue="profil"><TabsList><TabsTrigger value="profil"><UserCog />Profil</TabsTrigger><TabsTrigger value="securite"><Lock />Sécurité</TabsTrigger><TabsTrigger value="notifications"><Bell />Notifications</TabsTrigger></TabsList><TabsContent value="profil"><Panel><PanelTitle title="Profil personnel" subtitle="Informations visibles par l'équipe HABTI" /><form className="form-grid" onSubmit={(e)=>{e.preventDefault(); notify("Profil enregistré.");}}><Field label="Prénom"><TextInput defaultValue="Salma" /></Field><Field label="Nom"><TextInput defaultValue="Bennani" /></Field><Field label="E-mail"><TextInput type="email" defaultValue="salma@habtivoyage.com" /></Field><Field label="Téléphone"><TextInput defaultValue="+212 661 00 18 78" /></Field><Field label="Langue"><SelectInput options={["Français", "Arabe", "Anglais", "Espagnol"]} /></Field><Field label="Fuseau horaire"><SelectInput options={["Afrique/Casablanca", "Europe/Paris", "Europe/Madrid"]} /></Field><div className="field-full drawer-actions"><Button><Save />Enregistrer</Button></div></form></Panel></TabsContent><TabsContent value="securite"><Panel><PanelTitle title="Sécurité du compte" subtitle="Démonstration locale sans connexion externe" /><div className="switch-row"><div><b>Double authentification</b><span>Demander un code de vérification à la connexion.</span></div><Switch checked={doubleAuth} onCheckedChange={(v)=>{setDoubleAuth(v); notify(v?"Double authentification activée.":"Double authentification désactivée.");}} /></div><div className="drawer-actions"><Button variant="outline" onClick={()=>notify("Lien de réinitialisation envoyé en démonstration.")}>Réinitialiser le mot de passe</Button><Button onClick={()=>notify("Session sécurisée vérifiée.")}><ShieldCheck />Vérifier la session</Button></div></Panel></TabsContent><TabsContent value="notifications"><Panel><PanelTitle title="Préférences de notification" subtitle="Choisissez vos alertes personnelles" />{([ ["navigateur","Notifications navigateur"], ["email","Résumé par e-mail"], ["mobile","Alertes mobiles"] ] as const).map(([k,label])=><div className="switch-row" key={k}><div><b>{label}</b><span>Recevoir les informations importantes pour votre rôle.</span></div><Switch checked={notif[k]} onCheckedChange={(v)=>{setNotif((n)=>({...n,[k]:v})); notify(`${label} mis à jour.`);}} /></div>)}<div className="drawer-actions"><Button onClick={()=>notify("Préférences enregistrées.")}><Save />Enregistrer</Button></div></Panel></TabsContent></Tabs></div>;
}
