/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentCommunityManagerRouteImport } from './routes/agent-community-manager'
import { Route as AgentProspectionRouteImport } from './routes/agent-prospection'
import { Route as AgentServiceClientRouteImport } from './routes/agent-service-client'
import { Route as CampagnesRouteImport } from './routes/campagnes'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConseillerIaRouteImport } from './routes/conseiller-ia'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ParametresCompteRouteImport } from './routes/parametres-compte'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ServiceClientRouteImport } from './routes/service-client'
import { Route as AiThreadIdRouteImport } from './routes/ai.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CampagnesIdRouteImport } from './routes/campagnes.$id'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as CommunityManagerIndexRouteImport } from './routes/community-manager.index'
import { Route as CommunityManagerIdeesRouteImport } from './routes/community-manager.idees'
import { Route as CommunityManagerParametresRouteImport } from './routes/community-manager.parametres'
import { Route as CommunityManagerPlanningRouteImport } from './routes/community-manager.planning'
import { Route as DevisIdRouteImport } from './routes/devis.$id'
import { Route as EmployesIdRouteImport } from './routes/employes.$id'
import { Route as OperationsIdRouteImport } from './routes/operations.$id'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'
import { Route as CommunityManagerIdeesIdRouteImport } from './routes/community-manager.idees.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCommunityManagerRoute = AgentCommunityManagerRouteImport.update({
  id: '/agent-community-manager',
  path: '/agent-community-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProspectionRoute = AgentProspectionRouteImport.update({
  id: '/agent-prospection',
  path: '/agent-prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentServiceClientRoute = AgentServiceClientRouteImport.update({
  id: '/agent-service-client',
  path: '/agent-service-client',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesRoute = CampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseillerIaRoute = ConseillerIaRouteImport.update({
  id: '/conseiller-ia',
  path: '/conseiller-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresCompteRoute = ParametresCompteRouteImport.update({
  id: '/parametres-compte',
  path: '/parametres-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceClientRoute = ServiceClientRouteImport.update({
  id: '/service-client',
  path: '/service-client',
  getParentRoute: () => rootRouteImport,
} as any)
const AiThreadIdRoute = AiThreadIdRouteImport.update({
  id: '/ai/$threadId',
  path: '/ai/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesIdRoute = CampagnesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampagnesRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const CommunityManagerIndexRoute = CommunityManagerIndexRouteImport.update({
  id: '/community-manager/',
  path: '/community-manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityManagerIdeesRoute = CommunityManagerIdeesRouteImport.update({
  id: '/community-manager/idees',
  path: '/community-manager/idees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityManagerParametresRoute =
  CommunityManagerParametresRouteImport.update({
    id: '/community-manager/parametres',
    path: '/community-manager/parametres',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityManagerPlanningRoute =
  CommunityManagerPlanningRouteImport.update({
    id: '/community-manager/planning',
    path: '/community-manager/planning',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevisIdRoute = DevisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevisRoute,
} as any)
const EmployesIdRoute = EmployesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployesRoute,
} as any)
const OperationsIdRoute = OperationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OperationsRoute,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectsRoute,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReservationsRoute,
} as any)
const CommunityManagerIdeesIdRoute = CommunityManagerIdeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityManagerIdeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-community-manager': typeof AgentCommunityManagerRoute
  '/agent-prospection': typeof AgentProspectionRoute
  '/agent-service-client': typeof AgentServiceClientRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/conseiller-ia': typeof ConseillerIaRoute
  '/dashboard': typeof DashboardRoute
  '/devis': typeof DevisRouteWithChildren
  '/employes': typeof EmployesRouteWithChildren
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/missions': typeof MissionsRoute
  '/operations': typeof OperationsRouteWithChildren
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/parametres-compte': typeof ParametresCompteRoute
  '/planning': typeof PlanningRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/service-client': typeof ServiceClientRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/community-manager/idees': typeof CommunityManagerIdeesRouteWithChildren
  '/community-manager/parametres': typeof CommunityManagerParametresRoute
  '/community-manager/planning': typeof CommunityManagerPlanningRoute
  '/devis/$id': typeof DevisIdRoute
  '/employes/$id': typeof EmployesIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/community-manager/': typeof CommunityManagerIndexRoute
  '/community-manager/idees/$id': typeof CommunityManagerIdeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-community-manager': typeof AgentCommunityManagerRoute
  '/agent-prospection': typeof AgentProspectionRoute
  '/agent-service-client': typeof AgentServiceClientRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/conseiller-ia': typeof ConseillerIaRoute
  '/dashboard': typeof DashboardRoute
  '/devis': typeof DevisRouteWithChildren
  '/employes': typeof EmployesRouteWithChildren
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/missions': typeof MissionsRoute
  '/operations': typeof OperationsRouteWithChildren
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/parametres-compte': typeof ParametresCompteRoute
  '/planning': typeof PlanningRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/service-client': typeof ServiceClientRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/community-manager/idees': typeof CommunityManagerIdeesRouteWithChildren
  '/community-manager/parametres': typeof CommunityManagerParametresRoute
  '/community-manager/planning': typeof CommunityManagerPlanningRoute
  '/devis/$id': typeof DevisIdRoute
  '/employes/$id': typeof EmployesIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/community-manager': typeof CommunityManagerIndexRoute
  '/community-manager/idees/$id': typeof CommunityManagerIdeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-community-manager': typeof AgentCommunityManagerRoute
  '/agent-prospection': typeof AgentProspectionRoute
  '/agent-service-client': typeof AgentServiceClientRoute
  '/campagnes': typeof CampagnesRouteWithChildren
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/conseiller-ia': typeof ConseillerIaRoute
  '/dashboard': typeof DashboardRoute
  '/devis': typeof DevisRouteWithChildren
  '/employes': typeof EmployesRouteWithChildren
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/missions': typeof MissionsRoute
  '/operations': typeof OperationsRouteWithChildren
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/parametres-compte': typeof ParametresCompteRoute
  '/planning': typeof PlanningRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/service-client': typeof ServiceClientRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/community-manager/idees': typeof CommunityManagerIdeesRouteWithChildren
  '/community-manager/parametres': typeof CommunityManagerParametresRoute
  '/community-manager/planning': typeof CommunityManagerPlanningRoute
  '/devis/$id': typeof DevisIdRoute
  '/employes/$id': typeof EmployesIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/community-manager/': typeof CommunityManagerIndexRoute
  '/community-manager/idees/$id': typeof CommunityManagerIdeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-community-manager'
    | '/agent-prospection'
    | '/agent-service-client'
    | '/campagnes'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/conseiller-ia'
    | '/dashboard'
    | '/devis'
    | '/employes'
    | '/evenements'
    | '/factures'
    | '/missions'
    | '/operations'
    | '/paiements'
    | '/parametres'
    | '/parametres-compte'
    | '/planning'
    | '/prospects'
    | '/rapports'
    | '/reservations'
    | '/service-client'
    | '/ai/$threadId'
    | '/api/chat'
    | '/campagnes/$id'
    | '/clients/$id'
    | '/community-manager/idees'
    | '/community-manager/parametres'
    | '/community-manager/planning'
    | '/devis/$id'
    | '/employes/$id'
    | '/operations/$id'
    | '/prospects/$id'
    | '/reservations/$id'
    | '/community-manager/'
    | '/community-manager/idees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-community-manager'
    | '/agent-prospection'
    | '/agent-service-client'
    | '/campagnes'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/conseiller-ia'
    | '/dashboard'
    | '/devis'
    | '/employes'
    | '/evenements'
    | '/factures'
    | '/missions'
    | '/operations'
    | '/paiements'
    | '/parametres'
    | '/parametres-compte'
    | '/planning'
    | '/prospects'
    | '/rapports'
    | '/reservations'
    | '/service-client'
    | '/ai/$threadId'
    | '/api/chat'
    | '/campagnes/$id'
    | '/clients/$id'
    | '/community-manager/idees'
    | '/community-manager/parametres'
    | '/community-manager/planning'
    | '/devis/$id'
    | '/employes/$id'
    | '/operations/$id'
    | '/prospects/$id'
    | '/reservations/$id'
    | '/community-manager'
    | '/community-manager/idees/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-community-manager'
    | '/agent-prospection'
    | '/agent-service-client'
    | '/campagnes'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/conseiller-ia'
    | '/dashboard'
    | '/devis'
    | '/employes'
    | '/evenements'
    | '/factures'
    | '/missions'
    | '/operations'
    | '/paiements'
    | '/parametres'
    | '/parametres-compte'
    | '/planning'
    | '/prospects'
    | '/rapports'
    | '/reservations'
    | '/service-client'
    | '/ai/$threadId'
    | '/api/chat'
    | '/campagnes/$id'
    | '/clients/$id'
    | '/community-manager/idees'
    | '/community-manager/parametres'
    | '/community-manager/planning'
    | '/devis/$id'
    | '/employes/$id'
    | '/operations/$id'
    | '/prospects/$id'
    | '/reservations/$id'
    | '/community-manager/'
    | '/community-manager/idees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCommunityManagerRoute: typeof AgentCommunityManagerRoute
  AgentProspectionRoute: typeof AgentProspectionRoute
  AgentServiceClientRoute: typeof AgentServiceClientRoute
  CampagnesRoute: typeof CampagnesRouteWithChildren
  CatalogueRoute: typeof CatalogueRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ConseillerIaRoute: typeof ConseillerIaRoute
  DashboardRoute: typeof DashboardRoute
  DevisRoute: typeof DevisRouteWithChildren
  EmployesRoute: typeof EmployesRouteWithChildren
  EvenementsRoute: typeof EvenementsRoute
  FacturesRoute: typeof FacturesRoute
  MissionsRoute: typeof MissionsRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  ParametresCompteRoute: typeof ParametresCompteRoute
  PlanningRoute: typeof PlanningRoute
  ProspectsRoute: typeof ProspectsRouteWithChildren
  RapportsRoute: typeof RapportsRoute
  ReservationsRoute: typeof ReservationsRouteWithChildren
  ServiceClientRoute: typeof ServiceClientRoute
  AiThreadIdRoute: typeof AiThreadIdRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunityManagerIdeesRoute: typeof CommunityManagerIdeesRouteWithChildren
  CommunityManagerParametresRoute: typeof CommunityManagerParametresRoute
  CommunityManagerPlanningRoute: typeof CommunityManagerPlanningRoute
  CommunityManagerIndexRoute: typeof CommunityManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-community-manager': {
      id: '/agent-community-manager'
      path: '/agent-community-manager'
      fullPath: '/agent-community-manager'
      preLoaderRoute: typeof AgentCommunityManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-prospection': {
      id: '/agent-prospection'
      path: '/agent-prospection'
      fullPath: '/agent-prospection'
      preLoaderRoute: typeof AgentProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-service-client': {
      id: '/agent-service-client'
      path: '/agent-service-client'
      fullPath: '/agent-service-client'
      preLoaderRoute: typeof AgentServiceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes': {
      id: '/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof CampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseiller-ia': {
      id: '/conseiller-ia'
      path: '/conseiller-ia'
      fullPath: '/conseiller-ia'
      preLoaderRoute: typeof ConseillerIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres-compte': {
      id: '/parametres-compte'
      path: '/parametres-compte'
      fullPath: '/parametres-compte'
      preLoaderRoute: typeof ParametresCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-client': {
      id: '/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof ServiceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$threadId': {
      id: '/ai/$threadId'
      path: '/ai/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AiThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/$id': {
      id: '/campagnes/$id'
      path: '/$id'
      fullPath: '/campagnes/$id'
      preLoaderRoute: typeof CampagnesIdRouteImport
      parentRoute: typeof CampagnesRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/community-manager/': {
      id: '/community-manager/'
      path: '/community-manager'
      fullPath: '/community-manager/'
      preLoaderRoute: typeof CommunityManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-manager/idees': {
      id: '/community-manager/idees'
      path: '/community-manager/idees'
      fullPath: '/community-manager/idees'
      preLoaderRoute: typeof CommunityManagerIdeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-manager/parametres': {
      id: '/community-manager/parametres'
      path: '/community-manager/parametres'
      fullPath: '/community-manager/parametres'
      preLoaderRoute: typeof CommunityManagerParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-manager/planning': {
      id: '/community-manager/planning'
      path: '/community-manager/planning'
      fullPath: '/community-manager/planning'
      preLoaderRoute: typeof CommunityManagerPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/$id': {
      id: '/devis/$id'
      path: '/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof DevisIdRouteImport
      parentRoute: typeof DevisRoute
    }
    '/employes/$id': {
      id: '/employes/$id'
      path: '/$id'
      fullPath: '/employes/$id'
      preLoaderRoute: typeof EmployesIdRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/operations/$id': {
      id: '/operations/$id'
      path: '/$id'
      fullPath: '/operations/$id'
      preLoaderRoute: typeof OperationsIdRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/community-manager/idees/$id': {
      id: '/community-manager/idees/$id'
      path: '/$id'
      fullPath: '/community-manager/idees/$id'
      preLoaderRoute: typeof CommunityManagerIdeesIdRouteImport
      parentRoute: typeof CommunityManagerIdeesRoute
    }
  }
}

interface CampagnesRouteChildren {
  CampagnesIdRoute: typeof CampagnesIdRoute
}

const CampagnesRouteChildren: CampagnesRouteChildren = {
  CampagnesIdRoute: CampagnesIdRoute,
}

const CampagnesRouteWithChildren = CampagnesRoute._addFileChildren(
  CampagnesRouteChildren,
)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DevisRouteChildren {
  DevisIdRoute: typeof DevisIdRoute
}

const DevisRouteChildren: DevisRouteChildren = {
  DevisIdRoute: DevisIdRoute,
}

const DevisRouteWithChildren = DevisRoute._addFileChildren(DevisRouteChildren)

interface EmployesRouteChildren {
  EmployesIdRoute: typeof EmployesIdRoute
}

const EmployesRouteChildren: EmployesRouteChildren = {
  EmployesIdRoute: EmployesIdRoute,
}

const EmployesRouteWithChildren = EmployesRoute._addFileChildren(
  EmployesRouteChildren,
)

interface OperationsRouteChildren {
  OperationsIdRoute: typeof OperationsIdRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsIdRoute: OperationsIdRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface ProspectsRouteChildren {
  ProspectsIdRoute: typeof ProspectsIdRoute
}

const ProspectsRouteChildren: ProspectsRouteChildren = {
  ProspectsIdRoute: ProspectsIdRoute,
}

const ProspectsRouteWithChildren = ProspectsRoute._addFileChildren(
  ProspectsRouteChildren,
)

interface ReservationsRouteChildren {
  ReservationsIdRoute: typeof ReservationsIdRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsIdRoute: ReservationsIdRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

interface CommunityManagerIdeesRouteChildren {
  CommunityManagerIdeesIdRoute: typeof CommunityManagerIdeesIdRoute
}

const CommunityManagerIdeesRouteChildren: CommunityManagerIdeesRouteChildren = {
  CommunityManagerIdeesIdRoute: CommunityManagerIdeesIdRoute,
}

const CommunityManagerIdeesRouteWithChildren =
  CommunityManagerIdeesRoute._addFileChildren(
    CommunityManagerIdeesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCommunityManagerRoute: AgentCommunityManagerRoute,
  AgentProspectionRoute: AgentProspectionRoute,
  AgentServiceClientRoute: AgentServiceClientRoute,
  CampagnesRoute: CampagnesRouteWithChildren,
  CatalogueRoute: CatalogueRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ConseillerIaRoute: ConseillerIaRoute,
  DashboardRoute: DashboardRoute,
  DevisRoute: DevisRouteWithChildren,
  EmployesRoute: EmployesRouteWithChildren,
  EvenementsRoute: EvenementsRoute,
  FacturesRoute: FacturesRoute,
  MissionsRoute: MissionsRoute,
  OperationsRoute: OperationsRouteWithChildren,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  ParametresCompteRoute: ParametresCompteRoute,
  PlanningRoute: PlanningRoute,
  ProspectsRoute: ProspectsRouteWithChildren,
  RapportsRoute: RapportsRoute,
  ReservationsRoute: ReservationsRouteWithChildren,
  ServiceClientRoute: ServiceClientRoute,
  AiThreadIdRoute: AiThreadIdRoute,
  ApiChatRoute: ApiChatRoute,
  CommunityManagerIdeesRoute: CommunityManagerIdeesRouteWithChildren,
  CommunityManagerParametresRoute: CommunityManagerParametresRoute,
  CommunityManagerPlanningRoute: CommunityManagerPlanningRoute,
  CommunityManagerIndexRoute: CommunityManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
